FROM node:16-alpine3.17 as build

RUN mkdir /app
WORKDIR /app

COPY package.json ./
RUN yarn config set registry https://registry.npm.taobao.org
RUN yarn config set strict-ssl false 
RUN yarn
COPY . .
RUN yarn install
EXPOSE 3000
CMD ["node", "index.js"]