# Stage 1: Build the canteen service app
FROM node:20-alpine3.18 as build

RUN mkdir /app
WORKDIR /app

COPY package.json ./
RUN yarn
COPY . .
RUN yarn run build

# Stage 2: Copy the build output to node runtime
FROM node:20-alpine3.18

RUN mkdir /app
WORKDIR /app

COPY package.json ./
RUN yarn --prod

COPY --from=build /app/dist .
#COPY .env ./.env
ENV PORT=80
EXPOSE 80
CMD ["node", "index.js"]