# Stage 1: Build the canteen service app
FROM node:20-alpine3.18 as build

RUN mkdir /app
WORKDIR /app

COPY package.json ./
RUN npm config set registry https://registry.npm.taobao.org
RUN npm config set strict-ssl false 
RUN yarn config set registry https://registry.npm.taobao.org
RUN yarn config set strict-ssl false 
RUN yarn
COPY . .
RUN yarn run build

# Stage 2: Copy the build output to node runtime
FROM node:20-alpine3.18

RUN mkdir /app
WORKDIR /app

COPY package.json ./
RUN npm config set registry https://registry.npm.taobao.org
RUN npm config set strict-ssl false 
RUN yarn config set registry https://registry.npm.taobao.org
RUN yarn config set strict-ssl false 
RUN yarn --prod

COPY --from=build /app/dist .
ENV PORT=80
EXPOSE 80
CMD ["node", "index.js"]