# Stage 1: Build the React application
FROM node:20-alpine3.18 as build
WORKDIR /app
COPY . .
RUN yarn install
RUN yarn run build

# Stage 2: Serve the application with Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/canteen-app
