#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ./ GatewayService/

WORKDIR "/src/GatewayService"
RUN dotnet restore "GatewayService.csproj"

RUN dotnet build "GatewayService.csproj" -c Release --self-contained false -r linux-x64 -f net8.0 -o /app/build

FROM build AS publish
RUN dotnet publish "GatewayService.csproj" -c Release --self-contained false -r linux-x64 -f net8.0 -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "GatewayService.dll"]
