version: '3.8'

services:
  nginx:
    # image: nginx:latest
    build:
      context: .
      dockerfile: dockerfile
    container_name: nginx_container
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf