services:
  consulhost:
    image: consul:1.11.1
    command: agent -ui -server -bootstrap-expect=3 -node=consulhost -client=0.0.0.0 -datacenter hangzhou
    environment:
      CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
      CONSUL_BIND_INTERFACE: "eth0"
    expose:
      - "8300"
      - "8301"
      - "8302"
      - "8600"
    ports:
      - "8500:8500"
    networks:
      - cloud77_dev

  consulslave1:
    image: consul:1.11.1
    depends_on:
      - consulhost
    command: agent -server -node=consulslave1 -client=0.0.0.0 -datacenter hangzhou -retry-join consulhost
    environment:
      CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
      CONSUL_BIND_INTERFACE: "eth0"
    expose:
      - "8300"
      - "8301"
      - "8302"
      - "8600"
    networks:
      - cloud77_dev

  consulslave2:
    image: consul:1.11.1
    depends_on:
      - consulhost
    command: agent -server -node=consulslave2 -client=0.0.0.0 -datacenter hangzhou -retry-join consulhost
    environment:
      CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
      CONSUL_BIND_INTERFACE: "eth0"
    expose:
      - "8300"
      - "8301"
      - "8302"
      - "8600"
    networks:
      - cloud77_dev

networks:
  cloud77_dev:
    external: true
