#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ./ UserService/

WORKDIR "/src/UserService"
RUN dotnet restore "UserService.csproj"

RUN dotnet build "UserService.csproj" -c Release --self-contained false -r linux-x64 -f net8.0 -o /app/build

FROM build AS publish
RUN dotnet publish "UserService.csproj" -c Release --self-contained false -r linux-x64 -f net8.0 -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "UserService.dll"]
