# Build stage
FROM golang:1.21-alpine as build
ENV GOPROXY=https://goproxy.cn,direct
ENV GO_ENABLED=0
RUN mkdir /app
WORKDIR /app
COPY go.mod go.mod
RUN go mod download
COPY . .
RUN go build -o factory.exe

# Deploy stage
FROM alpine as final
EXPOSE 80
ENV GIN_MODE=release
RUN mkdir /app
WORKDIR /app
COPY --from=build /app/factory.exe ./factory.exe
COPY version ./version
COPY posts.json ./posts.json
COPY appsettings.json ./appsettings.json
CMD [ "./factory.exe" ]