name: build-npm-package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker Image Tag"
        required: true
        default: "latest"
      test_mode:
        description: "Flag value of test mode"
        required: false
        default: "true"

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: echo github ref
        run: echo ${{ github.ref }}

      - name: use node
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
          
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          node -v
          npm -v
          yarn -v
          ls
          pwd

      - name: Install package
        run: cd ./cloud77-typescript && yarn install
  
      - name: ESLint Check
        run: cd ./cloud77-typescript && yarn lint

      - name: Unit Test Check
        run: cd ./cloud77-typescript && yarn test-cc

      - name: Build and Bubble Package
        run: cd ./cloud77-typescript && yarn release

      - name: Prepare tar file
        run: cd ./cloud77-typescript/dist && npm pack

      - name: List files
        run: ls ./cloud77-typescript/dist