name: build-simple-service

on:

  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker Image Tag"
        required: true
        default: "0.0.0"
      push_to_registry:
        description: "Push to Image Registry"
        required: false
        default: "no"

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: echo github ref
        run: echo ${{ github.ref }}

      - name: set up docker
        uses: docker/setup-buildx-action@v1

      - name: echo docker version
        run: docker version

      - name: build image
        run: cd ./UserService && docker build -t registry.cn-hangzhou.aliyuncs.com/cloud_77/user-service:${{ github.event.inputs.image_tag }} .

      - name: list images
        run: docker images
    
      - if: github.event.inputs.push_to_registry == 'yes'
        name: Login to Aliyun Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_ACCESS_TOKEN }}

      - if: github.event.inputs.push_to_registry == 'yes'
        name: Push image
        run: docker push registry.cn-hangzhou.aliyuncs.com/cloud_77/user-service:${{ github.event.inputs.image_tag }}