name: main-action

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker Image Tag, E.g. v0.0.0"
        required: true
        default: "latest"
      test_mode:
        description: "Flag value of test mode"
        required: false
        default: "true"
  pull_request:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: echo github ref
        run: echo ${{ github.ref }}

      - name: use node
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      #   Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      #   Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          node -v
          npm -v
          yarn -v
          ls

      - name: Install package
        run: cd ./cloud77-typescript && yarn install

      - name: ESLint Check
        run: cd ./cloud77-typescript && yarn lint

      - name: Unit Test Check
        run: cd ./cloud77-typescript && yarn test-cc

      - name: Build Package
        run: cd ./cloud77-typescript && yarn build

      - name: Bubble package
        run: cd ./cloud77-typescript && yarn bubble

      - name: Prepare tar file
        run: cd ./cloud77-typescript/dist && npm pack

      - name: List files
        run: ls ./cloud77-typescript/dist