name: tester-run

on:

  workflow_dispatch:
    inputs:
      pkg_version:
        description: "Package version"
        required: true
        default: "0.0.0"
      test_mode:
        description: "Flag value of test mode"
        required: false
        default: "true"
  
  push:
    tags:
      - 'v*'

jobs:
  build-package:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: echo github ref
        run: echo ${{ github.ref }}

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          pwd

      - name: get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        
      - name: echo version
        run: echo ${{ steps.get_version.outputs.VERSION }}
